language: python
python:
  - "2.7"
 
before_install:
 - sudo apt-get install -y python-tidylib
 
 # Install dependencies
install:
 - pip install git+https://github.com/lbl-srg/BuildingsPy@master
 - shopt -s expand_aliases

# Execute tests
script:
 - cd Buildings && python ../bin/runUnitTests.py --validate-html-only
 - alias ls="ls -lh" && ls .
 
