language: python
python:
  - "2.7"
 
 # command to install dependencies
install: 
 - pip install python-tidylib
 - pip install git+https://github.com/lbl-srg/BuildingsPy@master

script:
 - python --version
 - cd Buildings && python ../bin/runUnitTests.py --validate-html-only
 
