language: python
python:
  - "2.7"
 
notifications:
  email: false

services:
  - docker
 
before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker pull michaelwetter/travis_ubuntu-1604_dymola-2017fd01-x86-64
  - sudo apt-get install -y \ 
      python-scipy \
      python-matplotlib \
      python-tidylib
  
# Install dependencies     - echo "ls -lh \"\$@\"" >> dymola
install:
  - pip install git+https://github.com/lbl-srg/BuildingsPy@master
  - sudo mv Resources/Scripts/travis/usr/local/bin/dymola /usr/local/bin/ 

# Execute tests
script:
  - cat /usr/local/bin/dymola
  - cd Buildings
  - python ../bin/runUnitTests.py --validate-html-only
  - python ../bin/runUnitTests.py -b
 
