language: python
python:
  - "2.7"
 
before_install:
 - sudo apt-get install -y python-tidylib
 
 # Install dependencies
install:
 - pip install git+https://github.com/lbl-srg/BuildingsPy@master
 - shopt -s expand_aliases
 - alias ls="ls -lh"
 - echo "#!/bin/bash" > /usr/bin/some_command.sh
 - echo "ls -lh $@" >> /usr/bin/some_command.sh
 - chmod +x /usr/bin/some_command.sh

# Execute tests
script:
 - cd Buildings && python ../bin/runUnitTests.py --validate-html-only
 - cat /usr/bin/some_command.sh
 - some_command Buildings
 
