language: python
python:
  - "2.7"

notifications:
  email: false

git:
  depth: 3

services:
  - docker

env:
  - UNITTESTS=--validate-html-only
  - UNITTESTS="-b -s Buildings.Controls.Continuous.Examples"
  - UNITTESTS="-b -s Buildings.Controls.Continuous.Validation"

# Enable system site packages in virtualenv so BuildingsPy sees scipy and matplotlib
virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker pull "$DOCKER_USERNAME"/travis_ubuntu-1604_dymola-2017fd01-x86-64

# Install dependencies     - echo "ls -lh \"\$@\"" >> dymola
install:
#  - sudo apt-get install -q python-tidylib
  - pip install git+https://github.com/lbl-srg/BuildingsPy@test-cli
  - sudo mv Buildings/Resources/Scripts/travis/usr/local/bin/dymola /usr/local/bin/

# Execute tests
script:
  - (cd Buildings && travis_wait 3600 python ../bin/runUnitTests.py $UNITTESTS)

after_failure:
  - cat Buildings/simulator.log
