language: python
python:
  - "2.7"
  
 # Install dependencies
install:
 - echo "#!/bin/bash" > some_command
 - echo "ls -lh $@" >> some_command
 - chmod +x some_command
 - sudo apt-get install -y python-tidylib
 - pip install git+https://github.com/lbl-srg/BuildingsPy@master
 - shopt -s expand_aliases
 - alias ls="ls -lh"
 

# Execute tests
script:
 - ls .
 - pwd
 - cat some_command
 - ./some_command Buildings
 - cd Buildings && python ../bin/runUnitTests.py --validate-html-only
 
