language: python
python:
  - "2.7"
 
before_install:
 - echo "#!/bin/bash" > some_command.sh
 - echo "ls -lh $@" >> some_command.sh
 - chmod +x some_command.sh
 - sudo apt-get install -y python-tidylib
 
 # Install dependencies
install:
 - pip install git+https://github.com/lbl-srg/BuildingsPy@master
 - shopt -s expand_aliases
 - alias ls="ls -lh"
 

# Execute tests
script:
 - cd Buildings && python ../bin/runUnitTests.py --validate-html-only
 - cat some_command.sh
 - ./some_command Buildings
 
